<?php 

?>
<div class="span3">
	<ul class="nav nav-list" style="width: 180px;">
	  <li class="nav-header"><?php t('我的账号','My account')?></li>
	  <li><a href="/account/index.php"><?php t('基本信息','Base Info')?></a></li>
	  <li><a href="/account/changepass.php"><?php t('修改密码','Change password')?></a></li>
	  <li class="nav-header">VPN</li>
	  <li><a href="/account/buy.php"><?php t('购买','Buy')?></a></li>
	  <li><a href="/account/recharge.php"><?php t('充值','Recharge')?></a></li>
<!-- 	  <li><a href="/account/servers.php">服务器列表</a></li> -->
<!-- 	  <li><a href="/account/accounts.php">登陆账号</a></li> -->
<!-- 	  <li><a href="/account/vpn_accounts.php">VPN账号</a></li> -->
<!-- 	  <li><a href="/account/invoice.php">购买记录</a></li> -->
	</ul>						
</div>
