<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">CNODE</a>
			<div class="nav-collapse collapse">
				<p class="navbar-text pull-right">
	              <a href="/logout.php" class="navbar-link">退出</a>
	            </p>
				<ul class="nav">
			      <li><a href="/index.php">首页</a></li>
			      <li><a href="/account/recharge.php">购买</a></li>
<!-- 			      <li><a href="/blog.php">Blog</a></li> -->
<!-- 					<li><a href="/community.php">社区</a></li> -->
			      <li class="active"><a href="index.php">我的账号</a></li>
			    </ul>				    
			</div>
	  </div>
	</div>
</div>
